//
//  DeviceTracker.h
//  MacGuarder
//
//  Created by GoKu on 14-7-24.
//  Copyright (c) 2014年 GoKuStudio. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <IOBluetooth/IOBluetooth.h>
#import <IOBluetoothUI/IOBluetoothUI.h>

static float const kTrackerTimeInteval  = 0.5;

static NSString * const kServiceName    = @"com.GoKuStudio.MacGuarder";             // service provided by iPhone installed with MacGuarder app
static NSString * const kServiceUUID    = @"3708ADE8-34FA-4FF6-82F8-8B4E3FCCAB1B";  // uuid generated by uuidgen

@class DeviceTracker;

typedef void (^DeviceRangeStatusUpdateBlock)(DeviceTracker *tracker);   // callback for updating device range status
typedef void (^DeviceSelectedBlock)(DeviceTracker *tracker);            // callback for select a device to monitor

@interface DeviceTracker : NSObject <IOBluetoothDeviceAsyncCallbacks>

@property (nonatomic, strong) IOBluetoothDevice *device;                // the device to be monitored
@property (nonatomic, assign) BluetoothHCIRSSIValue initialRSSI;
@property (nonatomic, assign) BluetoothHCIRSSIValue currentRSSI;

@property (nonatomic, assign) BOOL deviceInRange;
@property (nonatomic, assign) NSInteger inRangeThreshold;     // default is -70, range is (weak signal) -127..+20 (strong signal)
@property (nonatomic, readonly) BOOL isMonitoring;

@property (nonatomic, copy) DeviceRangeStatusUpdateBlock deviceRangeStatusUpdateBlock;
@property (nonatomic, copy) DeviceSelectedBlock deviceSelectedBlock;

+ (DeviceTracker *)sharedTracker;

- (void)selectDevice;
- (void)startMonitoring;
- (void)stopMonitoring;

@end
